baseURL = 'https://helpua.at'
languageCode = 'uk'
title = ''
theme = "hugo-book"
defaultContentLanguage = 'ua'
pluralizelisttitles = false
[languages]
    [languages.en]
        languageName = "🇺🇸 English"
        title = ""
        weight = 2
        contentDir = 'content.en'
    [languages.ua]
        languageName = "🇺🇦 yкраїнська"
        title = ""
        weight = 1

[params]
    BookTheme = 'auto'
    BookToC = false
    BookSection = '*'
    BookLogo = 'logo.jpeg'

[markup.goldmark.renderer]
unsafe= true